### ISSUE TITLE
taskLeaveVehicle

### ISSUE THREAD

**Issue by Mario2280** [alloc8or/gta5-nativedb-data#174]
taskLeaveVehicle all flags working the same

**Comment by alloc8or** [comment]
I have no clue what you're talking about. This is not a place where you should ask about scripting issues, we merely document Rockstar's stuff.

**Comment by Mario2280** [comment]
No it's not a question, it's a fact. In docs i found incorrent description. People told me in discord to write here for edits

**Comment by alloc8or** [comment]
In that case please make a PR to fix the incorrect description or provide some details instead of just saying `all flags working the same`.
