### ISSUE TITLE
some native missing

### ISSUE THREAD

**Issue by PliskinDev** [alloc8or/gta5-nativedb-data#189]
0xA921AA820C25702F = MISC::IS_BIT_SET
0x80C75307B1C42837 = STATS::GET_PACKED_BOOL_STAT_KEY
0x5BC62EC1937B9E5B = STATS::STAT_SET_BOOL_MASKED
0xF4D8E7AC2A27758C = STATS::GET_PACKED_BOOL_MASK
0xC4BB08EE7907471E = STATS::GET_PACKED_TU_BOOL_STAT_KEY
0x10FE3F1B79F9B071 = STATS::STAT_GET_BOOL_MASKED
0x7EEC2A316C250073 = STATS::_0x7EEC2A316C250073
0xE8F25DEEA400E4B6 = PED::_0xE8F25DEEA400E4B6
0xF08117067B87AD5F = SOCIALCLUB::_0xF08117067B87AD5F
0x0BB96F43A4C82904 =  SOCIALCLUB::SC_INBOX_MESSAGE_GET_DATA_FLOAT
0xAE3FEE8709B39DCB = VEHICLE::_0xAE3FEE8709B39DCB

**Comment by alloc8or** [comment]
Those were removed by R* and no longer exist in the game.
