### ISSUE TITLE
update some native parameter

### ISSUE THREAD

**Issue by PliskinDev** [alloc8or/gta5-nativedb-data#209]
SET_BLIP_SHORT_HEIGHT_THRESHOLD(Blip blip, BOOL toggle) //toggle is always 1
SET_BLIP_USE_HEIGHT_INDICATOR_ON_EDGE(Blip blip, BOOL toggle)
SET_WIDESCREEN_FORMAT(int wideFormatId) // wideFormatId 0,1,3,5
PAUSE_TOGGLE_FULLSCREEN_MAP(BOOL toggle)

**Comment by alloc8or** [comment]
Please submit a PR if you want to make param/comment changes, thanks.
