### ISSUE TITLE
Adding Native Patterns

### ISSUE THREAD

**Issue by alessandromrc** [alloc8or/gta5-nativedb-data#226]
Hi, I've made a JSON file that (should) contains all the patterns of the natives in the game and I think it would be a great addition to the DB. The repository which contains all the patterns is [here](https://github.com/alessandromrc/ThePatternDB).

**Comment by Ayimforgoroldacc** [comment]
Probably better luck here: https://github.com/DottieDot/GTAV-NativeDB/issues

**Comment by alessandromrc** [comment]
> Probably better luck here: https://github.com/DottieDot/GTAV-NativeDB/issues

Will look into this, thanks for letting me know. Will close this issue.
