### ISSUE TITLE
Question regarding the "Any*" arg type

### ISSUE THREAD

**Issue by LeonMrBonnie** [alloc8or/gta5-nativedb-data#75]
Hi,
looking at the arg types most of them are self explanatory, but the `Any*` argument type is a bit unclear.
Is an argument that has the `Any*` always a struct of some sort or does it indicate something else?

**Comment by alloc8or** [comment]
In most cases it's used to indicate 'this is a pointer to a struct', yes. _However_, it can also be a 'placeholder' for some other pointer type (e.g. ``char*``) if that param hasn't been properly documented yet.
Arguments of type ``Any`` can be _anything_ (as long as the data type is not larger than 64 bits) and arguments of type ``Any*`` definitely are pointer arguments but keep in mind that not all undocumented pointer arguments are listed as ``Any*`` here.

**Comment by LeonMrBonnie** [comment]
Thank you for the answer!
Is there some documentation available somewhere about these kind of "conventions" inside the project, or is this just something known to you and the frequent contributors? Maybe it would be helpful to add a bit of documentation to make these things clearer.
But that is out of the scope of this issue, thanks for answering my question.
